<head>
  <!--- <meta http-equiv="X-Frame-Options" content="allow">--->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="shortcut icon" href="/favicon.ico" type="image/vnd.microsoft.icon">

<!--  <link rel="stylesheet" media="all" href="/styles/print_styles.css"> -->
<!--	<link rel="stylesheet" media="all" href="/styles/rachelandrew_grid.css">-->

<!--
  <style>
    body { 
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    }

  	th, td {
  		border: 1px none #999;
  		padding: 0.1rem;
      vertical-align: top;
  	}
    h3 { margin: 5px;}
    ol { margin-top: 0px;}
  </style>
-->

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous">

  <link rel="stylesheet" href="public/styles/prism.css" data-noprefix />

  <link rel="stylesheet" type="text/css" href="public/styles/styles.css" media="all" />

  <script src="public/scripts/markdown.js"></script>

  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.6.3/showdown.min.js"></script>

  <script type="text/javascript" src="public/scripts/app.js"></script>

  <title>
    <cfoutput>#ucase(left(scope, 1))##right(scope, len(scope) - 1)#: #ucase(left(view, 1))##right(view, len(view) - 1)#</cfoutput>
  </title>
</head>
